@include('layouts.frontend.layout.header')
@include('layouts.frontend.layout.nav')
@include('layouts.frontend.layout.banner')
@include('layouts.frontend.layout.cause')
@include('layouts.frontend.layout.news')
@include('layouts.frontend.layout.event')
@include('layouts.frontend.layout.story')
@include('layouts.frontend.layout.footer')